### Stage 1: Build
FROM python:3.13-alpine AS builder
WORKDIR /app

# Copy requirements and install them into a dedicated folder for later reuse
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt --target=/app/dependencies

# Copy application code
COPY app.py .



### Stage 2: Final (Distroless)
FROM gcr.io/distroless/python3
# (distroless images default to non-root)
WORKDIR /app

# Copy installed dependencies and application code from the builder stage
COPY --from=builder /app/dependencies /app/dependencies
COPY --from=builder /app/app.py .

# Set environment variables. Workers are set to 3 for demonstration purposes
ENV PYTHONUNBUFFERED=1 \
    APP_VERSION=1.0.0 \
    PORT=5000 \
    GUNICORN_CMD_ARGS="--workers=3 --bind=0.0.0.0:5000" \
    PYTHONPATH=/app/dependencies

# Expose the port the app runs on
EXPOSE 5000

# Run the application
CMD ["gunicorn", "app:app"]
