name: Build and Deploy App

on:
  push:
    branches:
      - main
    paths:
      - 'app/**' # Only trigger if files in app change
  workflow_dispatch: # Allow manual triggering

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG=${{ github.sha }}

          docker build --no-cache -f app/Dockerfile -t $ECR_REGISTRY/flask_app:$IMAGE_TAG -t $ECR_REGISTRY/flask_app:latest app/ ### SYNC THIS WITH TERRAFORM TASK DEF

          docker push --all-tags $ECR_REGISTRY/flask_app

      - name: Update ECS to Use Latest Image
        run: |
          aws ecs update-service --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }} \
            --force-new-deployment
